Update runastrodriz to work with WFPC2 singletons
spacetelescope/drizzlepac pull request #1412
Opened 2022-07-07 23:44 UTC by stsci-hack

These changes add all the support necessary to successfully process WFPC2 images (at least full readout images) with 'runastrodriz', including alignment to GAIA.  This includes adding default parameter files under 'hap_pars/svm_parameters' for WFPC2 support based on WFC3/IR values.  Changes to 'haputils/analyze.py' were also implemented to account for the difference in keywords used to determine whether to process a WFPC2 image or not.

A new function was also added to 'drizzlepac/wfpc2Data.py' that converts the multiple GEIS-based WFPC2 MEF files into a single MEF with the same set of extensions as ACS or WFC3 MEF files.  Specifically, the 'c0m.fits' files provide the SCI extensions, while the 'c1m.fits' files serve as the DQ extensions and the ERR extension starts as a Poissonian estimate of the errors based on the SCI extension.  This creates an 'flt.fits' file consistent with ACS or WFC3 MEF files that then gets used for all subsequent processing.  
 
These changes were used to successfully create flt.fits files for all the exposures in the visit 'u5b806' where all the images were aligned to GAIAeDR3 with an rms of about 20mas using ~385 sources per exposure.

2022-07-08 21:12 UTC, mdlpstsci commented on drizzlepac/haputils/align_utils.py
> +            # detector = self.imghdu[0].header['detector']
Should this line just be deleted?

2022-07-08 23:43 UTC, stsci-hack commented on drizzlepac/haputils/align_utils.py
> +            # detector = self.imghdu[0].header['detector']
Removed in e9ca846.

2022-07-11 19:45 UTC, mdlpstsci approved these changes
Code updates done thus far look fine to me.  The configuration files are copies of WFC3/IR, so they are a good starting point.

2022-07-12 01:49 UTC, stsci-hack commented
This set of changes now supports full pipeline alignment to GAIA through `runastrodriz` as well as full SVM processing through `hapsequencer`.  This required the addition of rules files for WFPC2 products, parameter files for WFPC2 SVM (and MVM) processing based on WFC3/IR config files, and updates to SVM code as well.  These changes were tested on the 25 WFPC2 exposures of 47Tuc from visit **u5b806**.

2022-07-13 18:36 UTC, mdlpstsci commented on drizzlepac/haputils/align_utils.py
> +                if instrume.lower() == 'wfpc2' and 'detector' not in hdr0:
Is it safe to search for 'detector' (lower-case) here in hdr0?

2022-07-13 18:42 UTC, mdlpstsci requested changes
Just a question or two to resolve?

2022-07-13 20:29 UTC, mdlpstsci submitted a review, later dismissed

2022-07-13 21:17 UTC, mdlpstsci approved these changes
Oops.   I should have caught this issue!

2022-07-13 23:26 UTC, merged