Hla 1059 reference catalog weights are incorrect
spacetelescope/drizzlepac pull request #1616
Opened 2023-07-17 18:29 UTC by s-goldman

This PR corrects the weighting of the reference catalogs; the code now uses 1/sigma**2. The important lines of code are 283 and 284. I also added line 281 to avoid a possible divide by zero error. The remaining changes are the result of code formatting (black).

2023-07-17 19:36 UTC, mdlpstsci requested changes
Since SCSB only has a general set of standards (https://innerspace.stsci.edu/display/SCSB/Code+standards+refresher), and not a specific package we are supposed to use, I have tried to keep my opinion to myself.  However, there are a few places where I found the Black code updates to make the code harder to parse.  Please address these few items.

2023-07-17 19:36 UTC, mdlpstsci commented on drizzlepac/haputils/product.py
> +                                alignment_pars["determine_fit_quality"][
Same complaint as for Line 355.

2023-07-17 19:36 UTC, mdlpstsci commented on drizzlepac/haputils/product.py
> +                                alignment_pars["determine_fit_quality"][
Same complaint as for Line 355.

2023-07-17 19:36 UTC, mdlpstsci commented on drizzlepac/haputils/product.py
> +                                (
Please just revert the text for Lines 399-406 to the unBlack state which is easier to read (IMHO).

2023-07-18 21:24 UTC, mdlpstsci commented
@s-goldman Where is the update to the "wfpc2_wfpc2_index.json"?

2023-07-19 12:42 UTC, mdlpstsci commented
@s-goldman Oops.  I was checking both your PRs and made a comment in the wrong PR.  The change to the parameter index file needs to be in PR#1052 and not this PR for proper tracking of history.  Please remove the changes for config_utils.py from this PR and put into PR#1052.  Once that is done, this PR is ready to go.

2023-07-19 14:28 UTC, s-goldman commented
> @s-goldman Oops. I was checking both your PRs and made a comment in the wrong PR. The change to the parameter index file needs to be in PR#1052 and not this PR for proper tracking of history. Please remove the changes for config_utils.py from this PR and put into PR#1052. Once that is done, this PR is ready to go.

I'm sorry, I should have caught that. The change to config_utils is now in the HLA-1052 PR.

2023-07-19 14:45 UTC, mdlpstsci approved these changes
Thanks for all the fixes!

2023-07-19 14:58 UTC, merged