HLA-1111: Updated SVM filenames for WFPC2
spacetelescope/drizzlepac pull request #1678
Opened 2023-10-02 15:26 UTC by s-goldman

Resolves [HLA-1111](https://jira.stsci.edu/browse/HLA-1111)

Closes #1662 

This PR changes SVM filenames of WFPC2 products. The current SVM filenames follow the following structure:

`hst_<propid><obsetid><instr><detector><filter>_<ipppss>_dr[cz].fits`

where previously the `<instr>` and `<detector>` were both WFPC2. With these changes, the `<detector>` is forced to be "pc" if the `<instr> `is "WFPC2".

2023-10-02 18:53 UTC, s-goldman commented
I also had to change mentions of wfpc2_wfpc2 in filenames and json files to wfpc2_pc for the code to work properly.

2023-10-05 18:08 UTC, s-goldman commented
> @s-goldman Can you please check PR#1473 where Warren changed the names to include ...wfpc2_wfpc2... In his case he was eliminating both the use of _wf_ and _pc_. While I can see there are some unrelated changes his PR, it is good to check this PR to make sure all the necessary changes have been addressed by this PR. For example, the environment variable needed for SVM catalog generation for WFPC2 has not been updated in hapsequencer.py in this PR.

I've reverted the changes related to WFPC2 from #PR1473 and the code passes the jenkins regression tests. The github actions tests keep seeming to fail (on both of my current PRs), but the failures seem related to connection issues:

`Error: Connection broken: IncompleteRead(1061384 bytes read, 9591736 more expected)'`

It doesn't seem related to these code changes, but I could be wrong.

2023-10-09 14:52 UTC, mdlpstsci requested changes
Sorry (!) I know this is tedious, but I think we need to keep the nomenclature and file structure consistent across all instruments.  It looks like the [svm | mvm]_parameters need to have the subdirectories for WFPC2 renamed to wfpc2/pc/*.json.  This will also require changing the contents of the */index files.

2023-10-09 15:00 UTC, s-goldman commented
> Sorry (!) I know this is tedious, but I think we need to keep the nomenclature and file structure consistent across all instruments. It looks like the [svm | mvm]_parameters need to have the subdirectories for WFPC2 renamed to wfpc2/pc/*.json. This will also require changing the contents of the */index files.

No worries, I totally agree. Thanks for catching that. I've made the change in the most recent commit.

2023-10-09 15:58 UTC, mdlpstsci requested changes
The index file contents have to be updated, and then it is ready to go.

2023-10-09 15:58 UTC, mdlpstsci commented on drizzlepac/pars/hap_pars/mvm_parameters/wfpc2_pc_index.json
> +{
The filename paths in this file have to be updated.

2023-10-09 15:58 UTC, mdlpstsci commented on drizzlepac/pars/hap_pars/svm_parameters/wfpc2_pc_index.json
> +{
The filename paths in this file have to be updated.

2023-10-10 13:32 UTC, mdlpstsci approved these changes
Lots of nooks and crannies for this ticket!

2023-10-10 15:22 UTC, merged