HLA-1208 Removing TEAL GUI
spacetelescope/drizzlepac pull request #1759
Opened 2024-02-29 18:39 UTC by s-goldman

Resolves [HLA-1208](https://jira.stsci.edu/browse/HLA-1208)

Closes #1738 

This PR removed the TEAL GUI interface for drizzlepac. This PR does not make changes to teal.load calls which are still being used to load and parse ".cfg" configuration files. Much of this PR is removing documentation and adding comments that certain options are deprecated or no longer supported. The initial print statement of the available drizzlepac teal tasks has also been removed. 

**Checklist for maintainers**
- [ ] added entry in `CHANGELOG.rst` within the relevant release section
- [x] updated or added relevant tests
- [x] updated relevant documentation
- [ ] added relevant milestone
- [x] added relevant label(s)
- [ ] ran regression tests, post a link to the Jenkins job below.
      [How to run regression tests on a PR](https://github.com/spacetelescope/jwst/wiki/Running-Regression-Tests-Against-PR-Branches)

2024-02-29 18:44 UTC, mcara commented
🎆

2025-03-10 20:09 UTC, s-goldman commented on drizzlepac/__init__.py
hide_printed_output suppresses the teal import line from stsci.skypac.

2025-03-13 12:28 UTC, mdlpstsci commented on drizzlepac/drizCR.py
> -# this is the function that will be called from TEAL
I am not sure why this comment is removed.  This is a similar situation to createMedian.py Line 55.  I do not this it hurts to leave the comment as the function is still invoked.

2025-03-13 12:30 UTC, mdlpstsci commented on drizzlepac/mapreg.py
> -# TEAL Interface functions
Again, I do not think it hurts to keep the comments for context though you might modify the comment to indicate the TEAL interactive GUI is "disabled"or hidden, but some underlying functionality will remain (or something like this).

2025-03-13 12:31 UTC, mdlpstsci commented on drizzlepac/mdriz.py
> -        print('           -g: edit parameters with TEAL')
Just remove this line.

2025-03-13 12:33 UTC, mdlpstsci commented on drizzlepac/photeq.py
> -            If specifying multiple secondary photometric keywords in the TEAL
Here is where I might have left the comment and added some text indicating instruction may be removed in the future.

2025-03-13 12:35 UTC, mdlpstsci commented on drizzlepac/photeq.py
> -# TEAL Interface functions
Same as previous comment in a different module.  I would leave this for now with an added comment about TEAL being disabled and removing this text and/or functionality if the future (or something like this).

2025-03-13 12:35 UTC, mdlpstsci commented on drizzlepac/pixreplace.py
> -# TEAL Interfaces
Same comment as left in photeq.py.

2025-03-13 12:36 UTC, mdlpstsci commented on drizzlepac/pixtopix.py
> -# --------------------------
Same comment as photeq.py.

2025-03-13 12:36 UTC, mdlpstsci commented on drizzlepac/pixtosky.py
> -# TEAL Interface functions
Same comment as in photeq.py.

2025-03-13 12:38 UTC, mdlpstsci commented on drizzlepac/processInput.py
> -    as set by the user with TEAL. If no configObj is given, it will retrieve
I would leave this as removing the mention of TEAL may make the remainder of the text not exactly make sense or the function does not work as implied.

2025-03-13 12:39 UTC, mdlpstsci commented on drizzlepac/processInput.py
> -    Used primarily for TEAL interface.
Do not remove comment.  Just add text the function may be deprecated as the use of the TEAL GUI is being disabled.

2025-03-13 12:42 UTC, mdlpstsci commented on drizzlepac/sky.py
> -#this is the function that will be called from TEAL
Similar comments here as made in other files.  Either leave the comment and add further documentation or remove comment and functionality.

2025-03-13 12:44 UTC, mdlpstsci commented on drizzlepac/skytopix.py
> -# TEAL Interface functions
Same comments as made in previous modules.

2025-03-13 12:44 UTC, mdlpstsci commented on drizzlepac/staticMask.py
> -# this is called by the TEAL interface
Same comments as made in previous modules.

2025-03-13 12:45 UTC, mdlpstsci commented on drizzlepac/tweakback.py
> -#### TEAL Interfaces to run this task
Same comments as made in previous modules.

2025-03-13 12:46 UTC, mdlpstsci commented on drizzlepac/updatenpol.py
> -#
Same comments as in previous modules.

2025-03-13 12:52 UTC, mdlpstsci commented on drizzlepac/adrizzle.py
> -# ###  User level interface to run drizzle tasks from TEAL
Same comment as previous modules.  Either leave the comment and add more doc indicating TEAL GUI being removed, but some functionality will remain as a convenience to reading default parameters from where?

2025-03-13 13:06 UTC, mdlpstsci requested changes
Sorry, I did have a lot of comments, but many of them are redundant.  I would leave comments with TEAL for context at this time.  If the functionality being called will be invoked when TEAL GUI is "disabled", then I would add more commentary indicating how the functionality is being used and where it is getting its information as the GUI input is not available.  When the TEAL GUI is officially turned off, some (perhaps not all) support functions will also be deprecated/deleted.  At that time, the comment and function can be deleted.  If functionality is being kept as it is general and useful, then a comment should be added if it is invoked as "teal.something()" that the TEAL GUI is no longer supported, but the underlying TEAL functionality is still useful.

Sorry, you might have done this already, but I think it is useful to say.  Before you remove any actual TEAL functionality, I would run the tasks _with_ and _without_ the TEAL GUI to understand/see how and which functions are invoked.  Also, there is some text that implies the TEAL GUI has state (i.e., some variables have preset and/or saved values).  Where is this state maintained?  Where are the default values for the configObj maintained when the user does not invoke the TEAL GUI?  Are the default values for the configObj and any preset values for TEAL GUI the coming from the same source?

2025-03-13 15:52 UTC, mdlpstsci requested changes
After some discussion, it is understood that it is very difficult to run the TEAL GUI at this time. 

The high level summary of my comments/suggestions for requested changes really amount to NOT deleting some of the comments regarding TEAL GUI until the actual functionality is removed or rewritten so that breadcrumbs for TEAL support functionality remain in place.

2025-03-13 21:07 UTC, s-goldman commented
moved over to #1975

2025-03-13 21:07 UTC, closed without merging