HLA:1061 final_fillval set to fill in values when WHT=0
spacetelescope/drizzlepac pull request #1767
Opened 2024-03-12 17:51 UTC by s-goldman

Resolves [HLA-1061](https://jira.stsci.edu/browse/HLA-1061)

Closes #1613 

This PR reverts a previous change: PR #1222. We are re-enabling the behavior that pixels with WHT=0 are still filled in with any available value. This includes bad pixel and fuzzy edge areas. The code has been tested with ipppssoot u65q06 which successfully fills in WHT=0 areas and still produces the desired S_REGION. 

Work still to do is allowing the options of a fillvalue of nan when desired by users. 

**Checklist for maintainers**
- [ ] added entry in `CHANGELOG.rst` within the relevant release section
- [ ] updated or added relevant tests
- [ ] updated relevant documentation
- [ ] added relevant milestone
- [ ] added relevant label(s)
- [ ] ran regression tests, post a link to the Jenkins job below.
      [How to run regression tests on a PR](https://github.com/spacetelescope/jwst/wiki/Running-Regression-Tests-Against-PR-Branches)

2024-03-12 17:52 UTC, s-goldman commented
A Note: The Jenkins test PR (#1766) needs to be merged before this one.

2024-03-18 13:35 UTC, mdlpstsci commented on tests/drizzle/test_kernel.py
> +    # check that orginal bad pixel flux still coming through:
Fix spelling: orginal -> original

2024-03-18 14:27 UTC, mdlpstsci requested changes
Just a small typo to fix.  I added "Re-enable" to the title of this issue as this ticket is not creating new functionality, but re-enabling previous functionality.  Also, this PR does not seem (to me) to resolve fully HLA-1061 (or am I misunderstanding)?  It seems that ticket has a portion to add a new option.  Please let me know where I am misunderstanding.

2024-03-18 15:02 UTC, mdlpstsci approved these changes

2024-03-18 15:34 UTC, mcara approved these changes

2024-03-18 16:05 UTC, merged