Fixes codecov
spacetelescope/drizzlepac pull request #1816
Opened 2024-06-13 18:58 UTC by jhunkeler

* Fixes missing python 3.11 test commands

2024-06-13 19:08 UTC, mdlpstsci commented on JenkinsfileRT
> +bc2.test_cmds = ["pytest --env=${artifactory_env} --cov=./ --basetemp=tests_output --junitxml=results.xml --bigdata",
Should this be "b3" instead of "b2"?

2024-06-13 19:17 UTC, mdlpstsci requested changes
Chastised for not leaving a comment.  I believe the "b2" should be "b3" on or around line 67.

2024-06-13 21:03 UTC, mdlpstsci approved these changes

2024-06-13 22:15 UTC, merged

2024-06-20 13:57 UTC, s-goldman commented
It looks like we also need to `pip install pytest-cov` in order for the --cov command to work for the 3.11 test.