Update runastrodriz to work under Windows
spacetelescope/drizzlepac pull request #794
Opened 2020-09-02 21:40 UTC by stsci-hack

These fairly simple, and blunt, changes address problems that prevented `runastrodriz` from successfully executing to completion under Windows (the OS).  The changes are:
* insure that `num_cores` parameter value as set by the user gets passed to `astrodrizzle` when generating the a posteriori drizzle products 
* added `try...except` block around the deletion of the astrodrizzle log file in `run_driz`
* A note was added to the `runastrodriz` sphinx docs to suggest that users set `num_cores` to 1 when running under Windows due to problems with threaded logging (or, in fact, lack of any working logging when using multiprocessing as we have it implemented now in `astrodrizzle`). 

In addition, a few (PEP8) Flake8 syntax errors were also corrected.

2020-09-03 13:38 UTC, mdlpstsci commented on drizzlepac/runastrodriz.py
> +    # hlet = headerlet.Headerlet.fromfile(headerlet_file)
Is this meant to be commented out?

2020-09-03 14:06 UTC, mdlpstsci requested changes
One question which needs to be answered and otherwise this PR is ready for merging.

2020-09-10 01:22 UTC, stsci-hack commented on drizzlepac/runastrodriz.py
> +    # hlet = headerlet.Headerlet.fromfile(headerlet_file)
Fixed under 11fdea6.

2020-09-10 01:25 UTC, stsci-hack commented
The changes in this PR now enforce single-CPU operations when running under Windows for both AstroDrizzle (single-drizzle step) and runsinglehap for the upcoming SVM processing.  This will need to be revised once the logging can be updated by resolving #799.

2020-09-15 14:50 UTC, merged