Singlevisit documentation update
spacetelescope/drizzlepac pull request #947
Opened 2021-02-22 20:25 UTC by dulude

**Associated JIRA tickets**
- [HLA-305](https://jira.stsci.edu/browse/HLA-305)

**High-level Summary**
- This PR contains a number of updates/changes/tweaks to the singlevisit.rst documentation file.
- There were also updates/changes/tweaks to several other .rst files, as well as docstrings in a couple of python scripts. These were both in support of the singlevisit.rst updates, as well as stand-alone fixes to other documentation issues that I encountered.
- There is also the initial commit of sourcelist_flag_breakdown.py, a code which simple gives the flag break down for a single user-specified .ecsv catalog file.

**Specific Changes**

2021-02-23 18:08 UTC, mdlpstsci commented on doc/source/catalog_generation.rst
> +    65368 are filtered out. Users can adjust this value using a custom input parameter file and changing the
Maybe the flag value got changed in the code, but it also needs to be changed to "5" here.

2021-02-23 19:17 UTC, mdlpstsci requested changes
Just a few minor changes.  It is important to get this update merged as there are yet more changes being done by other team members describing specialized updates.

2021-02-23 20:12 UTC, dulude commented on doc/source/singlevisit.rst
> +  * **asn.fits** : suffix for the association table
issue resolved by commit [0f93085](https://github.com/spacetelescope/drizzlepac/pull/947/commits/0f930854c3d1ead3966a8b999bf7a94a2d8c7426)

2021-02-23 20:32 UTC, dulude commented on doc/source/singlevisit.rst
> +  #. copy the pipeline-calibrated (FLT/FLC) files to the current directory for processing
Issue resolved by commit [cb9f38e](https://github.com/spacetelescope/drizzlepac/pull/947/commits/cb9f38e913d1d312cb750cb720f5d48a95134c41)

2021-02-23 20:41 UTC, mdlpstsci approved these changes

2021-02-24 16:41 UTC, mdlpstsci approved these changes
All issues addressed.

2021-02-24 16:41 UTC, merged